In [1]:
import numpy as np


In [2]:
x = np.arange(10)

In [3]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
x+x


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [5]:
x*50


array([  0,  50, 100, 150, 200, 250, 300, 350, 400, 450])

In [6]:
x/x


C:\Users\a\AppData\Local\Temp\ipykernel_19160\2465823206.py:1: RuntimeWarning: invalid value encountered in divide
  x/x


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [7]:
1/x


C:\Users\a\AppData\Local\Temp\ipykernel_19160\3975751982.py:1: RuntimeWarning: divide by zero encountered in divide
  1/x


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [8]:
x**5 #üssünü alma

array([    0,     1,    32,   243,  1024,  3125,  7776, 16807, 32768,
       59049], dtype=int32)

In [9]:
np.sqrt(x)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [10]:
np.exp(x)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [11]:
np.max(x)

9

In [12]:
np.min(x)

0

In [13]:
np.log(x)

C:\Users\a\AppData\Local\Temp\ipykernel_19160\1277889159.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(x)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])